config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/prices'
  post '/home/prices' => 'home/prices'
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    #grab news data
    @url = 'https://min-api.cryptocompare.com/data/v2/news/?lang=EN'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @news = JSON.parse(@response)

    
    #grab price data
    @prices_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,XRP,ETH,BCH,EOS,LTC,ADA,XLM,MIOTA,USDT,TRX&tsyms=USD,EUR'
    @prices_uri = URI(@prices_url)
    @prices_response = Net::HTTP.get(@prices_uri)
    @prices_crypto = JSON.parse(@prices_response)

    
  end

  
  def prices 
    require 'net/http'
    require 'json'
    @symbol = params[:sym]
    if @symbol
    @symbol = @symbol.upcase

    #grab price data
    @quote_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=' + @symbol +  '&tsyms=USD,EUR'
    @quote_uri = URI(@quote_url)
    @quote_response = Net::HTTP.get(@quote_uri)
    @quote = JSON.parse(@quote_response)

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <%= link_to "Crypt News Network", root_path, class: 'navbar - brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     
      <li class="nav-item">
      <%=link_to "Get Prices", home_prices_path, class: 'nav-link' %>
      </li>
      
    </ul>
    <%=form_tag home_prices_path, :method =>'POST', class:"form-inline my-2 my-lg-0" do%>
    <%=text_field_tag 'sym', nil, placeholder: 'Enter Crypto Symbol', class:"form-control mr-sm-2"%>
    <%=submit_tag 'Lookup', class:"btn btn-outline-secondary my-2 my-sm-0" %>
    <%end%>
  </div>
</nav>



 

app/views/home/index.html.erb
<table class="table table-sm table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">24hr High</th>
      <th scope="col">24hr Low</th>
      <th scope="col">Market Cap</th>
    </tr>
     </thead>
    <tbody>
    <%@prices_crypto["DISPLAY"].each do |key, value|%>
    <tr>
      <td><%= key%></td>
      <td><%= value["USD"]["PRICE"]%></td>
      <td><%= value["USD"]["HIGHDAY"]%></td>
      <td><%= value["USD"]["LOWDAY"]%></td>
      <td><%= value["USD"]["MKTCAP"]%></td>
    </tr>
    <%end%>
  </tbody>
</table>

<br/>

<%@news["Data"]%>
    <div class="container">
    <div class="row">
        <%for x in @news["Data"]%> 
            <div class="col-sm">
            <div class="card" style="width: 18rem;">
            <img src="<%= x["imageurl"] %>" class="card-img-top" alt="<%= x["source"]%>">
            <div class="card-body">
                <h5 class="card-title"><%= x["title"]%></h5>
                <p class="card-text"><%= x["body"]%></p>
                <a href="<%= x["url"]%>" class="btn btn-secondary">Read More.. </a>
                </div>
             </div>
            <br/>
        </div>
    <%end%>
 </div>
</div>

app/views/home/prices.html.erb
<%if @symbol%>
<%if @quote["Response"]%>
<h3> That Symbol <%=@symbol%> Doesnt't Exist. Please Try Again..</h3>
<%else%>
     <%@quote["DISPLAY"].each do |key, value|%>
          <div class="jumbotron">
           <h1 class="display-4"><%= key %></h1>
            Price: <%= value["USD"]["PRICE"]%> <br/>
            24 hr High:<%= value["USD"]["HIGHDAY"]%><br/>
            24 hr Low: <%= value["USD"]["LOWDAY"]%><br/>
            Market Cap: <%= value["USD"]["MKTCAP"]%><br/>
        </div>   
        <%end%>
        <%end%>
<%else%>
<h4>Please enter a crypto symbol in the form above..</h4>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto News Network</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   <%= render 'home/navbar'%>
  <br/>
  <div class = "contatiner">
    <%= yield %>
    </div>
  </body>
</html>